# Two-tailed test

Este teste é muito utilizado em **testes de qualidade**. Outro exemplo é a avaliação de peças que devem ter um encaixe perfeito (porcas e parafusos, chaves e fechaduras).

In [26]:
import pandas as pd
from scipy.stats import norm
import numpy as np
from statsmodels.stats.weightstats import ztest

## <font color='red'>Problema</font>

Nossa produtora de vinhos produz garrafas de 500 ml. Seu processo de produção é quase todo automatizado e as garrafas são preenchidas por uma máquina que às vezes apresenta um certo desajuste, levando a erros no preenchimento das mesmas para mais ou menos conteúdo. Quando o volume médio cai abaixo de 500 ml, a empresa se preocupa em perder vendas e ter problemas com os orgãos fiscalizadores. Quando o volume passa de 500 ml, a empresa começa a se preocupar com prejuízos no processo de produção.

O setor de controle de qualidade da empresa extrai, periodicamente, amostras de 50 garrafas para monitorar o processo de produção. Para cada amostra, é realizado um teste de hipóteses para avaliar se o maquinário se desajustou. A equipe de controle de qualidade assume um nível de significância de 5%.

Suponha agora que uma amostra de 50 embalagens foi selecionada e que a média amostral observada foi de 503,24 ml. Esse valor de média amostral é suficientemente maior que 500 ml para nos fazer rejeitar a hipótese de que a média do processo é de 500 ml ao nível de significância de 5%?

![Teste Bicaudal](https://caelum-online-public.s3.amazonaws.com/1229-estatistica-parte3/01/img005.png)

## Problem data

In [4]:
sample = [509, 505, 495, 510, 496, 509, 497, 502, 503, 505, 
          501, 505, 510, 505, 504, 497, 506, 506, 508, 505, 
          497, 504, 500, 498, 506, 496, 508, 497, 503, 501, 
          503, 506, 499, 498, 509, 507, 503, 499, 509, 495, 
          502, 505, 504, 509, 508, 501, 505, 497, 508, 507]

sample_df = pd.DataFrame(sample, columns=['Sample'])
sample_df.head()

Sample
0     509
1     505
2     495
3     510
4     496

In [7]:
sample_mean = sample_df.mean()

sample_mean

Sample    503.24
dtype: float64

In [8]:
sample_std = sample_df.std()

sample_std

Sample    4.483803
dtype: float64

In [9]:
# information from problem statement
mean = 500
significance = 0.05
confidence = 1 - significance
n = 50

## Step 1: Formulation of hypothesis $H_0$ and $H_1$

#### <font color='red'>Lembre-se, a hipótese nula sempre contém a alegação de igualdade</font>

### $H_0: \mu = 500$

### $H_1: \mu \neq 500$

## Step 2: Choosing the appropriate sample distribution

<img src='https://caelum-online-public.s3.amazonaws.com/1229-estatistica-parte3/01/img003.png' width=70%>

- Is the sample size greater than 30?
YES!


- Is the population standard deviation known?
NO!

## Step 3: Fixing the test significance ($\alpha$)

In [11]:
probability = (0.5 + (confidence / 2))
probability

0.975

## Getting $z_{\alpha/2}$

In [14]:
z_alpha_2 = norm.ppf(probability)

z_alpha_2

1.959963984540054

![Região de Aceitação](https://caelum-online-public.s3.amazonaws.com/1229-estatistica-parte3/01/img006.png)

## Step 4: calculation of the test statistic and verification of this value with the acceptance and rejection areas of the test

# $$z = \frac{\bar{x} - \mu_0}{\frac{s}{\sqrt{n}}}$$

In [16]:
z = (sample_mean - mean) / (sample_std / np.sqrt(n))

z

Sample    5.10956
dtype: float64

![Estatística-Teste](https://caelum-online-public.s3.amazonaws.com/1229-estatistica-parte3/01/img007.png)

- Z is on the rejected area.

## Step 5: Acceptance or rejection of the null hypothesis

<img src='https://caelum-online-public.s3.amazonaws.com/1229-estatistica-parte3/01/img013.png' width=90%>

### <font color='red'>Critério do valor crítico</font>

> ### Teste Bicaudal
> ### Rejeitar $H_0$ se $z \leq -z_{\alpha / 2}$ ou se $z \geq z_{\alpha / 2}$

In [18]:
z <= -z_alpha_2

Sample    False
dtype: bool

In [19]:
z >= z_alpha_2

Sample    True
dtype: bool

- As one of the statements $z \leq -z_{\alpha / 2}$ or $z \geq z_{\alpha / 2}$ is True, then we rejected the null hypothesis -  as we saw with the figure.

### <font color='green'>Conclusão: Como a média amostral $\bar{x}$ é significativamente maior que 500 ml, rejeitamos $H_0$. Neste caso, devem ser tomadas providências para ajustar o maquinário que preenche as embalagens.</font>

### <font color='red'>Critério do $p-valor$</font>

> ### Teste Bicaudal
> ### Rejeitar $H_0$ se o valor $p\leq\alpha$

In [21]:
p_value = 2*(1 - norm.cdf(z))

p_value

array([3.22910317e-07])

In [22]:
p_value <= significance

array([ True])

- Through the p_value, we alse see that we should reject the null hypothesis.

## Ztest

In [27]:
z, p_value = ztest(x1=sample_df, value=mean)

In [28]:
z

array([5.10955978])

In [30]:
p_value

array([3.22910317e-07])

In [31]:
p_value <= significance

array([ True])